theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US

title: Dongwook
description: 이것저것 적어두는 곳
url: "https://dongwook.org"
baseurl: ""
lang: ko
timezone: Asia/Seoul

date_format: "%Y-%m-%d"

google_fonts:
  - name: "Noto Sans KR"
    weights: "400,700"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Site Author
author:
  email:
  links:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
